spring:
  security:
    user:
      name: admin
      password: 1234

  datasource:
    url: jdbc:postgresql://localhost:5432/gira
    username: postgres
    password: postgres
    
  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
logging:
  level:
    root: info
    '[cybersoft.javabackend.java16giraphuc]': debug